### PR TITLE
Add snapd 2.31.1, remove snap-confine [subsumed by]. Remove systemd f…

### PR DESCRIPTION
**Pull request by damobrisbane**
Updated for snapd v2.31.1.

NB: 
1) folder sys-apps[/snap-confine] removed, was incorporated into snapd core.
2) unfortunately I don't run systemd, hence was removed as ebuild dependency and systemd_dounit tests were commented out of ebuild. This may not be desirable for you.

### CODE REVIEW

**Comment by Zaxim** [comment]
Are you missing the ebuild file for 2.31.1?

**Comment by damobrisbane** [comment]
oops... will send through update

**Comment by damobrisbane** [comment]
NB: systemd parts comments out; dont have a system to test these parts. Could uncomment and rebuild manifest and expect it's good.

**Comment by sophietheopossum** [comment]
my understanding seems to be that snap-confine is needed for the older versions? if you're removing snap-confine wouldn't you need to remove the older versions too? also isn't systemd a hard requirement? (i know you already acknowledged this somewhat obviously) the new ebuild seems solid enough though, seeing as this repo seems to be relatively inactive i'm making a new one (it's about time snaps got an overlay!) and i'll make sure to include the new ebuild. please bare with me if i make any mistakes i'm relatively new to gentoo.

**Pull request closed without merging**
